apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drobinator2-pvc
  namespace: bioinfo
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  volumeName: drobinator2-pv
  accessModes:
  - ReadOnlyMany
  storageClassName: local-storage
