---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry
  namespace: harbor
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chartmuseum
  namespace: harbor
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jobservice
  namespace: harbor
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database
  namespace: harbor
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
  namespace: harbor
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trivy
  namespace: harbor
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
