apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: strain-col-proj
  namespace: bioinfo
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
