apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyterhub-storage
  namespace: bioinfo
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
