apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: galaxy-postgres
  namespace: argocd
  labels:
    argocd.cyril/label: work
    argocd.cyril/exposure: external
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to.
  project: default

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://k8s-control.test:6443
    namespace: bioinfo

  # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 0

  # Source of the application manifests
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: 'postgresql'
    targetRevision: 10.3.17
    path: ''

    helm:
      releaseName: galaxy
      version: v3
      values: |
        global:
          postgresql:
            storageClass: rook-cephfs
        persistence:
          enabled: true
          existingClaim: galaxy-postgres
          accessModes:
          - ReadWriteMany
        volumePermissions:
          enabled: true
          securityContext:
            runAsUser: 0
        postgresqlUsername: galaxydbuser
        postgresqlDatabase: galaxy
        existingSecret: galaxy-db-secret
        replication:
          enabled: false
          readReplicas: 2
          synchronousCommit: "on"
          numSynchronousReplicas: 1
        tls:
          enabled: false
          certificatesSecret: galaxy-cert
          certFilename: tls.crt
          certKeyFilename: tls.key
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
        rbac:
          create: true
        psp:
          create: true
