---
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v16.2.2

  dataDirHostPath: /var/lib/rook

  crashCollector:
    disable: true

# cleanupPolicy:
#  deleteDataDirOnHosts:#yes-really-destroy-data

  network:
    provider: host

  mgr:
    modules:
      - name: pg_auto_scaler
        enabled: true

  mon:
    count: 3
    allowMultiplePerNode: false

  storage:
    useAllNodes: false
    useAllDevices: false
    config:
      storeType: "bluestore"

    nodes:
    - name: "arnold"
      devices:
      - name: "sda"
        config:
          metadataDevice: "sdd3"
      - name: "sdb"
        config:
          metadataDevice: "sdd3"
      - name: "sdc"
        config:
          metadataDevice: "sdd3"
      - name: "sdd4"
    - name: "bernard"
      devices:
      - name: "sda"
        config:
          metadataDevice: "sdd3"
      - name: "sdb"
        config:
          metadataDevice: "sdd3"
      - name: "sdc"
        config:
          metadataDevice: "sdd3"
      - name: "sdd4"
    - name: "dolores"
      devices:
      - name: "nvme0n1p3"

  monitoring:
    enabled: true

  dashboard:
    enabled: true
    port: 8843
    ssl: true
